[package]
name = "launcher"
version = "3.0.1"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"
default-run = "launcher"

[[bin]]
path = "src/main_launcher.rs"
name = "launcher"

[dependencies]
cottontail = { path = "../cottontail"}
gif = "0.10.0"
indexmap = "1.6.1"
rayon = "1.5.0"
color-art = "0.3"

